Action()
{


	web_url("Ê×Ò³", 
		"URL=http://127.0.0.1:8888/discuz/upload/forum.php", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=", 
		"Snapshot=t1.inf", 
		"Mode=HTML", 
		EXTRARES, 
		"Url=static/image/common/background.png", ENDITEM, 
		"Url=static/image/common/px.png", ENDITEM, 
		"Url=static/image/common/newarow.gif", ENDITEM, 
		"Url=static/image/common/pn.png", ENDITEM, 
		"Url=static/image/common/nv_a.png", ENDITEM, 
		"Url=static/image/common/nv.png", ENDITEM, 
		"Url=static/image/common/search.png", ENDITEM, 
		"Url=static/image/common/arrwd.gif", ENDITEM, 
		"Url=static/image/common/qmenu.png", ENDITEM, 
		"Url=static/image/common/titlebg.png", ENDITEM, 
		"Url=static/image/common/pt_item.png", ENDITEM, 
		"Url=static/image/common/chart.png", ENDITEM, 
		"Url=static/image/common/scrolltop.png", ENDITEM, 
		"Url=static/image/common/tip_bottom.png", ENDITEM, 
		LAST);


	web_submit_data("Ëæ»úµÇÂ¼", 
		"Action=http://127.0.0.1:8888/discuz/upload/member.php?mod=logging&action=login&loginsubmit=yes&infloat=yes&lssubmit=yes&inajax=1", 
		"Method=POST", 
		"TargetFrame=", 
		"RecContentType=text/xml", 
		"Referer=http://127.0.0.1:8888/discuz/upload/forum.php", 
		"Snapshot=t2.inf", 
		"Mode=HTML", 
		ITEMDATA, 
		"Name=fastloginfield", "Value=username", ENDITEM, 
		"Name=username", "Value={uname}", ENDITEM, 
		"Name=password", "Value={pwd}", ENDITEM, 
		"Name=quickforward", "Value=yes", ENDITEM, 
		"Name=handlekey", "Value=ls", ENDITEM, 
		LAST);


	web_url("forum.php_2", 
		"URL=http://127.0.0.1:8888/discuz/upload/forum.php", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=", 
		"Snapshot=t3.inf", 
		"Mode=HTML", 
		EXTRARES, 
		"Url=static/image/common/user_online.gif", ENDITEM, 
		"Url=static/image/common/notice.gif", ENDITEM, 
		"Url=static/image/common/style_switch.png", ENDITEM, 
		"Url=static/js/common_extra.js?61K", ENDITEM, 
		LAST);


	/*web_url("Ëæ»úµã»÷°å¿é", 
		"URL=http://127.0.0.1:8888/discuz/upload/forum.php?mod=forumdisplay&fid={fid}", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=http://127.0.0.1:8888/discuz/upload/forum.php", 
		"Snapshot=t4.inf", 
		"Mode=HTML", 
		EXTRARES, 
		"Url=static/image/common/titlebg_sd.png", "Referer=http://127.0.0.1:8888/discuz/upload/forum.php?mod=forumdisplay&fid=2", ENDITEM, 
		"Url=static/image/common/fav.gif", "Referer=http://127.0.0.1:8888/discuz/upload/forum.php?mod=forumdisplay&fid=2", ENDITEM, 
		"Url=static/image/common/feed.gif", "Referer=http://127.0.0.1:8888/discuz/upload/forum.php?mod=forumdisplay&fid=2", ENDITEM, 
		"Url=static/image/common/arw_r.gif", "Referer=http://127.0.0.1:8888/discuz/upload/forum.php?mod=forumdisplay&fid=2", ENDITEM, 
		"Url=static/image/common/arw_l.gif", "Referer=http://127.0.0.1:8888/discuz/upload/forum.php?mod=forumdisplay&fid=2", ENDITEM, 
		"Url=static/image/common/refresh.png", "Referer=http://127.0.0.1:8888/discuz/upload/forum.php?mod=forumdisplay&fid=2", ENDITEM, 
		"Url=static/image/common/atarget.png", "Referer=http://127.0.0.1:8888/discuz/upload/forum.php?mod=forumdisplay&fid=2", ENDITEM, 
		"Url=static/js/smilies.js?61K", "Referer=http://127.0.0.1:8888/discuz/upload/forum.php?mod=forumdisplay&fid=2", ENDITEM, 
		"Url=static/image/editor/editor.gif", "Referer=http://127.0.0.1:8888/discuz/upload/forum.php?mod=forumdisplay&fid=2", ENDITEM, 
		"Url=static/image/common/pollsmall.gif", "Referer=http://127.0.0.1:8888/discuz/upload/forum.php?mod=forumdisplay&fid=2", ENDITEM, 
		"Url=data/cache/common_smilies_var.js?61K", "Referer=http://127.0.0.1:8888/discuz/upload/forum.php?mod=forumdisplay&fid=2", ENDITEM, 
		"Url=static/image/smiley/default/biggrin.gif", "Referer=http://127.0.0.1:8888/discuz/upload/forum.php?mod=forumdisplay&fid=2", ENDITEM, 
		"Url=static/image/smiley/default/smile.gif", "Referer=http://127.0.0.1:8888/discuz/upload/forum.php?mod=forumdisplay&fid=2", ENDITEM, 
		"Url=static/image/smiley/default/sad.gif", "Referer=http://127.0.0.1:8888/discuz/upload/forum.php?mod=forumdisplay&fid=2", ENDITEM, 
		"Url=static/image/smiley/default/cry.gif", "Referer=http://127.0.0.1:8888/discuz/upload/forum.php?mod=forumdisplay&fid=2", ENDITEM, 
		"Url=static/image/smiley/default/shocked.gif", "Referer=http://127.0.0.1:8888/discuz/upload/forum.php?mod=forumdisplay&fid=2", ENDITEM, 
		"Url=static/image/smiley/default/tongue.gif", "Referer=http://127.0.0.1:8888/discuz/upload/forum.php?mod=forumdisplay&fid=2", ENDITEM, 
		"Url=static/image/smiley/default/funk.gif", "Referer=http://127.0.0.1:8888/discuz/upload/forum.php?mod=forumdisplay&fid=2", ENDITEM, 
		"Url=static/image/smiley/default/hug.gif", "Referer=http://127.0.0.1:8888/discuz/upload/forum.php?mod=forumdisplay&fid=2", ENDITEM, 
		"Url=static/image/smiley/default/dizzy.gif", "Referer=http://127.0.0.1:8888/discuz/upload/forum.php?mod=forumdisplay&fid=2", ENDITEM, 
		"Url=static/image/smiley/default/victory.gif", "Referer=http://127.0.0.1:8888/discuz/upload/forum.php?mod=forumdisplay&fid=2", ENDITEM, 
		"Url=static/image/smiley/default/time.gif", "Referer=http://127.0.0.1:8888/discuz/upload/forum.php?mod=forumdisplay&fid=2", ENDITEM, 
		"Url=static/image/smiley/default/handshake.gif", "Referer=http://127.0.0.1:8888/discuz/upload/forum.php?mod=forumdisplay&fid=2", ENDITEM, 
		"Url=static/image/smiley/default/shutup.gif", "Referer=http://127.0.0.1:8888/discuz/upload/forum.php?mod=forumdisplay&fid=2", ENDITEM, 
		"Url=static/image/smiley/default/kiss.gif", "Referer=http://127.0.0.1:8888/discuz/upload/forum.php?mod=forumdisplay&fid=2", ENDITEM, 
		"Url=static/image/smiley/default/call.gif", "Referer=http://127.0.0.1:8888/discuz/upload/forum.php?mod=forumdisplay&fid=2", ENDITEM, 
		"Url=static/image/smiley/default/sleepy.gif", "Referer=http://127.0.0.1:8888/discuz/upload/forum.php?mod=forumdisplay&fid=2", ENDITEM, 
		"Url=static/image/smiley/default/huffy.gif", "Referer=http://127.0.0.1:8888/discuz/upload/forum.php?mod=forumdisplay&fid=2", ENDITEM, 
		"Url=static/image/smiley/default/shy.gif", "Referer=http://127.0.0.1:8888/discuz/upload/forum.php?mod=forumdisplay&fid=2", ENDITEM, 
		"Url=static/image/smiley/default/titter.gif", "Referer=http://127.0.0.1:8888/discuz/upload/forum.php?mod=forumdisplay&fid=2", ENDITEM, 
		"Url=static/image/smiley/default/sweat.gif", "Referer=http://127.0.0.1:8888/discuz/upload/forum.php?mod=forumdisplay&fid=2", ENDITEM, 
		"Url=static/image/smiley/default/mad.gif", "Referer=http://127.0.0.1:8888/discuz/upload/forum.php?mod=forumdisplay&fid=2", ENDITEM, 
		"Url=static/image/smiley/default/loveliness.gif", "Referer=http://127.0.0.1:8888/discuz/upload/forum.php?mod=forumdisplay&fid=2", ENDITEM, 
		"Url=static/image/smiley/default/lol.gif", "Referer=http://127.0.0.1:8888/discuz/upload/forum.php?mod=forumdisplay&fid=2", ENDITEM, 
		"Url=static/image/smiley/default/curse.gif", "Referer=http://127.0.0.1:8888/discuz/upload/forum.php?mod=forumdisplay&fid=2", ENDITEM,
		LAST);*/

	web_url("loadrunner", 
		"URL=http://127.0.0.1:8888/discuz/upload/forum.php?mod=forumdisplay&fid={fid}", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=http://127.0.0.1:8888/discuz/upload/forum.php", 
		"Snapshot=t6.inf", 
		"Mode=HTML", 
		EXTRARES, 
		"Url=static/image/common/dot.gif", "Referer=http://127.0.0.1:8888/discuz/upload/forum.php?mod=forumdisplay&fid=36", ENDITEM, 
		LAST);


	return 0;
}